apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
        - name: yolo
          image: deemaa/yolo-dev:74
          ports:
            - containerPort: 5000
          resources: # ✅ required for HPA
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"



---
apiVersion: v1
kind: Service
metadata:
  name: yolo-service
  namespace: dev
spec:
  selector:
    app: yolo
  ports:
    - port: 5000
      targetPort: 5000
