apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
        - name: yolo
          image: deemaa/yolo-prod:39
          ports:
            - containerPort: 5000