apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: k8s/monitoring
    repoURL: https://github.com/DeemaAbuHwaij/PolybotInfraFursa
    targetRevision: HEAD
  project: default