apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polybot-prod
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    path: k8s/Polybot
    repoURL: https://github.com/DeemaAbuHwaij/PolybotInfraFursa
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true