apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yolo-dev
  name: yolo-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-dev
  template:
    metadata:
      labels:
        app: yolo-dev
    spec:
      containers:
      - env:
          - name: POLYBOT_URL
            valueFrom:
              secretKeyRef:
                name: yolo-secrets-dev
                key: POLYBOT_URL
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: yolo-secrets-dev
                key: S3_BUCKET_NAME
          - name: QUEUE_URL
            valueFrom:
              secretKeyRef:
                name: yolo-secrets-dev
                key: QUEUE_URL
          - name: STORAGE_TYPE
            valueFrom:
              secretKeyRef:
                name: yolo-secrets-dev
                key: STORAGE_TYPE
        image: deemaa/yolo-dev:74
        name: yolo-container
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi



---
apiVersion: v1
kind: Service
metadata:
  name: yolo-service
  namespace: dev
  labels:
    app: yolo-dev
    monitoring: "true"
spec:
  selector:
    app: yolo-dev
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: yolo-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      monitoring: "true"
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - port: http
      path: /metrics
      interval: 15s





