# PURPOSE: This workflow provisions the AWS infrastructure for a Kubernetes cluster using Terraform
# whenever code is pushed to the main branch.

name: Provision K8s Infrastructure

on:
  push:
    branches:
      - main

jobs:
  provision:
    name: Terraform Apply Infra
    runs-on: ubuntu-latest

    env:
      # These environment variables are used by Terraform to authenticate with AWS
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-west-1

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Set up Terraform CLI version 1.5.7
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      # Step 3: Initialize Terraform in the 'tf' directory
      - name: Terraform Init
        working-directory: tf
        run: terraform init

      # Step 4: Select or create the Terraform workspace for 'us-west-1'
      - name: Select Terraform Workspace
        working-directory: tf
        run: terraform workspace select us-west-1 || terraform workspace new us-west-1

      # Step 5: Run a Terraform plan using region-specific variables
      - name: Terraform Plan
        working-directory: tf
        run: terraform plan -var-file="region.us-west-1.tfvars"

      # Step 6: Apply the Terraform plan automatically
      - name: Terraform Apply
        working-directory: tf
        run: terraform apply -auto-approve -var-file="region.us-west-1.tfvars"

