name: Provision Kubernetes Infra

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Apply Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4

      - name: Terraform Init
        run: terraform init
        working-directory: tf/

      - name: Select or Create Workspace
        run: terraform workspace select us-west-1 || terraform workspace new us-west-1
        working-directory: tf/

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=region.us-west-1.tfvars
        working-directory: tf/
