name: Provision K8s Infrastructure

on:
  push:
    branches:
      - main

jobs:
  provision:
    name: Terraform Apply Infra
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: tf
        run: terraform init

      - name: Select Terraform Workspace
        working-directory: tf
        run: terraform workspace select us-west-1 || terraform workspace new us-west-1

      - name: Terraform Plan
        working-directory: tf
        run: terraform plan -var-file="region.us-west-1.tfvars"

      - name: Terraform Apply
        working-directory: tf
        run: terraform apply -auto-approve -var-file="region.us-west-1.tfvars"
