name: Deploy Nginx Container to Dev

on:
  push:
    paths:
      - "nginx-config/polybot-dev.conf"
      - "scripts/deploy_nginx_container.sh"
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Copy Nginx config + deploy script to Dev EC2
      run: |
        scp -i key.pem -o StrictHostKeyChecking=no nginx-config/polybot-dev.conf ubuntu@${{ secrets.DEV_HOST }}:/home/ubuntu/conf.d/
        scp -i key.pem -o StrictHostKeyChecking=no scripts/deploy_nginx_container.sh ubuntu@${{ secrets.DEV_HOST }}:/home/ubuntu/

    - name: Run Nginx Docker container on Dev EC2
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.DEV_HOST }} << 'EOF'
          chmod +x /home/ubuntu/deploy_nginx_container.sh
          bash /home/ubuntu/deploy_nginx_container.sh
        EOF
