name: Deploy Nginx Container to Prod

on:
  push:
    paths:
      - "nginx-config/polybot-prod.conf"
      - "scripts/deploy_nginx_container.sh"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Copy Nginx config + deploy script to Prod EC2
      run: |
        scp -i key.pem -o StrictHostKeyChecking=no nginx-config/polybot-prod.conf ubuntu@${{ secrets.PROD_HOST }}:/home/ubuntu/conf.d/
        scp -i key.pem -o StrictHostKeyChecking=no scripts/deploy_nginx_container.sh ubuntu@${{ secrets.PROD_HOST }}:/home/ubuntu/

    - name: Run Nginx Docker container on Prod EC2
      run: |
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.PROD_HOST }} << 'EOF'
          chmod +x /home/ubuntu/deploy_nginx_container.sh
          bash /home/ubuntu/deploy_nginx_container.sh
        EOF
