name: Deploy Nginx Config to Dev

on:
  push:
    paths:
      - "nginx-config/default.conf"
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Copy Nginx config file to Dev EC2
      run: |
        scp -i key.pem -o StrictHostKeyChecking=no nginx-config/default.conf ubuntu@${{ secrets.DEV_HOST }}:/tmp/
        
        ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@${{ secrets.DEV_HOST }} << 'EOF'
          sudo mv /tmp/default.conf /etc/nginx/conf.d/
          sudo nginx -t && sudo systemctl reload nginx
        EOF
