name: Deploy NGINX & Polybot (Dev)

on:
  push:
    paths:
      - 'k8s/**'
      - '.github/workflows/nginx-deploy-dev.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_DEV }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    - name: Apply Namespace & Polybot (Dev)
      run: |
        kubectl apply -f k8s/namespaces/dev.yaml
        kubectl apply -f k8s/Polybot/deployment.yaml -n dev

    - name: Apply Ingress (Dev)
      run: |
        kubectl apply -f k8s/Polybot/ingress.yaml -n dev