name: Deploy NGINX & Polybot (Prod)

on:
  push:
    paths:
      - 'k8s/**'
      - '.github/workflows/nginx-deploy-prod.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_DEV }}" | base64 -d > ~/.kube/config

        chmod 600 ~/.kube/config

    - name: Apply Namespace & Polybot (Prod)
      run: |
        kubectl apply -f k8s/namespaces/prod.yaml
        kubectl apply -f k8s/Polybot/deployment.yaml -n prod

    - name: Apply Ingress (Prod)
      run: |
        kubectl apply -f k8s/Polybot/ingress.yaml -n prod